"""Durable Job Repository, cooperative scheduler, and injected worker APIs."""

from .io import CorruptJSONLError, append_jsonl, atomic_write_json, read_json
from .io import read_jsonl_tolerant, repair_jsonl_tail
from .models import (
    ACTIVE_JOB_STATUSES,
    RECOVERABLE_JOB_STATUSES,
    SCHEMA_VERSION,
    TERMINAL_JOB_STATUSES,
    CommandReceipt,
    JobCommand,
    JobCounts,
    JobEvent,
    JobLease,
    JobRequest,
    JobResourceState,
    JobState,
    JobStatus,
    PruneCandidate,
    PrunePreview,
    PruneResult,
    RecordCheckpoint,
    RecordStatus,
    RecoveryDecision,
    ShardState,
)
from .repository import (
    DEFAULT_HEARTBEAT_SECONDS,
    DEFAULT_LEASE_STALE_SECONDS,
    FileJobRepository,
    ImmutableRecordError,
    JobNotFoundError,
    JobRepositoryError,
    LeaseConflictError,
    RevisionConflictError,
    compute_config_hash,
    hash_config_file,
)
from .scheduler import (
    ResourcePolicy,
    ResourceProbe,
    ResourceScheduler,
    ResourceSnapshot,
    SchedulerDecision,
    default_max_active_jobs,
)
from .worker import AsyncJobRunner, JobRunResult, JobWorker

__all__ = [
    "ACTIVE_JOB_STATUSES",
    "AsyncJobRunner",
    "CommandReceipt",
    "CorruptJSONLError",
    "DEFAULT_HEARTBEAT_SECONDS",
    "DEFAULT_LEASE_STALE_SECONDS",
    "FileJobRepository",
    "ImmutableRecordError",
    "JobCommand",
    "JobCounts",
    "JobEvent",
    "JobLease",
    "JobNotFoundError",
    "JobRepositoryError",
    "JobRequest",
    "JobResourceState",
    "JobRunResult",
    "JobState",
    "JobStatus",
    "JobWorker",
    "LeaseConflictError",
    "PruneCandidate",
    "PrunePreview",
    "PruneResult",
    "RECOVERABLE_JOB_STATUSES",
    "RecordCheckpoint",
    "RecordStatus",
    "RecoveryDecision",
    "ResourcePolicy",
    "ResourceProbe",
    "ResourceScheduler",
    "ResourceSnapshot",
    "RevisionConflictError",
    "SCHEMA_VERSION",
    "SchedulerDecision",
    "ShardState",
    "TERMINAL_JOB_STATUSES",
    "append_jsonl",
    "atomic_write_json",
    "compute_config_hash",
    "default_max_active_jobs",
    "hash_config_file",
    "read_json",
    "read_jsonl_tolerant",
    "repair_jsonl_tail",
]
